use_frameworks!

platform :ios, '8.0'

target 'SMCategory_Example' do
  pod 'SMCategory', :path => '../'

  target 'SMCategory_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
